/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#003f87',
        'primary-container': '#0056b3',
        'primary-fixed': '#d7e2ff',
        'primary-fixed-dim': '#acc7ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#bbd0ff',
        'on-primary-fixed': '#001a40',
        'on-primary-fixed-variant': '#004491',
        'secondary': '#585f68',
        'secondary-container': '#dde3ee',
        'secondary-fixed': '#dde3ee',
        'secondary-fixed-dim': '#c1c7d1',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#5e656e',
        'on-secondary-fixed': '#161c24',
        'on-secondary-fixed-variant': '#414750',
        'tertiary': '#722b00',
        'tertiary-container': '#983c00',
        'tertiary-fixed': '#ffdbcc',
        'tertiary-fixed-dim': '#ffb694',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffc2a7',
        'on-tertiary-fixed': '#351000',
        'on-tertiary-fixed-variant': '#7b2f00',
        'surface': '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-variant': '#e1e3e4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-tint': '#115cb9',
        'on-surface': '#191c1d',
        'on-surface-variant': '#424752',
        'background': '#f8f9fa',
        'on-background': '#191c1d',
        'outline': '#727784',
        'outline-variant': '#c2c6d4',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'inverse-primary': '#acc7ff',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
