const PDFDocument = require('pdfkit')

function generateComparisonPDF(products) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 0, size: 'A4', layout: 'landscape' })
    const chunks = []
    doc.on('data', (c) => chunks.push(c))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    const W = doc.page.width   // 842 (landscape)
    const H = doc.page.height  // 595
    const M = 45

    const navy   = '#0a2463'
    const blue   = '#1e5fa8'
    const accent = '#3a86ff'
    const white  = '#ffffff'
    const border = '#e5e7eb'
    const muted  = '#6b7280'
    const dark   = '#111827'

    // Header Band
    doc.rect(0, 0, W, 100).fill(navy)
    doc.fillColor(white).font('Helvetica-Bold').fontSize(24)
       .text('PharmaLink', M, 35, { continued: true })
       .font('Helvetica').fillColor('#93c5fd').text(' Comparison Matrix')
    
    doc.fillColor('#93c5fd').font('Helvetica').fontSize(10)
       .text('Technical Product Analysis & Evaluation', M, 65)

    let y = 140
    const colWidth = (W - M * 2) / (products.length + 1)
    const fieldWidth = colWidth

    const fields = [
      { key: 'name', label: 'Product Name' },
      { key: 'genericName', label: 'Generic / Strength' },
      { key: 'brand', label: 'Manufacturer' },
      { key: 'category', label: 'Category' },
      { key: 'packageSize', label: 'Packaging' },
      { key: 'description', label: 'Technical Details' }
    ]

    // Table Header Background
    doc.rect(M, y - 10, W - M * 2, 30).fill('#f1f5f9')
    doc.fillColor(navy).font('Helvetica-Bold').fontSize(9)
    doc.text('PARAMETERS', M + 10, y)

    products.forEach((p, i) => {
      doc.text(p.name.toUpperCase(), M + colWidth * (i + 1), y, { width: colWidth - 10, align: 'center' })
    })

    y += 35

    fields.forEach((field, fIdx) => {
      // Background for alternating rows
      if (fIdx % 2 !== 0) {
        doc.rect(M, y - 10, W - M * 2, 40).fill('#f8fafc')
      }

      doc.fillColor(muted).font('Helvetica-Bold').fontSize(8).text(field.label.toUpperCase(), M + 10, y)
      
      products.forEach((p, i) => {
        doc.fillColor(dark).font('Helvetica').fontSize(9)
           .text(p[field.key] || '—', M + colWidth * (i + 1), y, { width: colWidth - 10, align: 'center' })
      })

      // Divider
      doc.moveTo(M, y + 25).lineTo(W - M, y + 25).strokeColor(border).lineWidth(0.5).stroke()
      y += 45
    })

    // Footer
    const footerY = H - 40
    doc.rect(0, footerY, W, 40).fill(navy)
    doc.fillColor('#93c5fd').font('Helvetica').fontSize(8)
       .text('Generated by PharmaLink Wholesale Procurement Systems', M, footerY + 15)
    doc.text(new Date().toLocaleDateString(), 0, footerY + 15, { width: W - M, align: 'right' })

    doc.end()
  })
}

module.exports = { generateComparisonPDF }
