-- Additional products for all categories
-- Run in pgAdmin Query Tool on the pharmalink database

INSERT INTO products (name, generic_name, brand, category, package_size, description, image_url, is_active, is_featured) VALUES

-- ── PRESCRIPTION ─────────────────────────────────────────────────────────────
('Amoxicillin 500mg',       'Amoxicillin Trihydrate',    'GlaxoSmithKline', 'prescription', 'Box of 100 Capsules',        'Broad-spectrum antibiotic for bacterial infections.',                    'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80', true, true),
('Atorvastatin 20mg',       'Atorvastatin Calcium',      'Pfizer Inc.',     'prescription', 'Pack of 30 Tablets',         'Statin medication for lowering cholesterol.',                            'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&q=80', true, true),
('Metformin HCL 1000mg',    'Metformin Hydrochloride',   'Bayer Healthcare','prescription', 'Box of 60 Tablets',          'First-line medication for type 2 diabetes.',                             'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=600&q=80', true, false),
('Lisinopril 10mg',         'Lisinopril',                'Pfizer Inc.',     'prescription', 'Bottle of 30 Tablets',       'ACE inhibitor for hypertension and heart failure.',                      'https://images.unsplash.com/photo-1576671081837-49000212a370?w=600&q=80', true, false),
('Lantus SoloStar',         'Insulin Glargine',          'Sanofi S.A.',     'prescription', '5 x 3ml Prefilled Pens',     'Long-acting insulin for diabetes management.',                           'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80', true, true),
('Nexium 40mg',             'Esomeprazole Magnesium',    'AstraZeneca',     'prescription', 'Box of 28 Gastro-Resistant Tabs','Proton pump inhibitor for acid reflux.',                             'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80', true, false),
('Entresto 97/103mg',       'Sacubitril/Valsartan',      'Novartis AG',     'prescription', 'Box of 56 Tablets',          'Heart failure medication combining sacubitril and valsartan.',           'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=600&q=80', true, false),
('Amlodipine 5mg',          'Amlodipine Besylate',       'Pfizer Inc.',     'prescription', 'Box of 30 Tablets',          'Calcium channel blocker for hypertension and angina.',                   'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=600&q=80', true, false),
('Omeprazole 20mg',         'Omeprazole',                'AstraZeneca',     'prescription', 'Box of 28 Capsules',         'Proton pump inhibitor for gastric ulcers and GERD.',                     'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&q=80', true, false),
('Losartan 50mg',           'Losartan Potassium',        'Merck & Co.',     'prescription', 'Box of 30 Tablets',          'Angiotensin receptor blocker for hypertension.',                         'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80', true, false),
('Simvastatin 40mg',        'Simvastatin',               'Merck & Co.',     'prescription', 'Box of 30 Tablets',          'HMG-CoA reductase inhibitor for hypercholesterolemia.',                  'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=600&q=80', true, false),
('Ciprofloxacin 500mg',     'Ciprofloxacin HCl',         'Bayer AG',        'prescription', 'Box of 20 Tablets',          'Fluoroquinolone antibiotic for urinary and respiratory infections.',     'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=600&q=80', true, false),
('Warfarin 5mg',            'Warfarin Sodium',           'Bristol-Myers',   'prescription', 'Box of 100 Tablets',         'Anticoagulant for prevention of blood clots.',                           'https://images.unsplash.com/photo-1576671081837-49000212a370?w=600&q=80', true, false),
('Levothyroxine 100mcg',    'Levothyroxine Sodium',      'Abbott Labs',     'prescription', 'Box of 100 Tablets',         'Thyroid hormone replacement therapy.',                                   'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&q=80', true, false),
('Gabapentin 300mg',        'Gabapentin',                'Pfizer Inc.',     'prescription', 'Box of 100 Capsules',        'Anticonvulsant for neuropathic pain and epilepsy.',                      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80', true, false),

-- ── OTC ──────────────────────────────────────────────────────────────────────
('Aspirin Protect 100mg',   'Acetylsalicylic Acid',      'Bayer AG',        'otc', 'Box of 100 Tablets',         'Low-dose aspirin for cardiovascular protection.',                        'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&q=80', true, true),
('Paracetamol 500mg',       'Acetaminophen',             'Generic Pharma',  'otc', 'Box of 100 Tablets',         'Analgesic and antipyretic for pain and fever.',                          'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=600&q=80', true, false),
('Ibuprofen 400mg',         'Ibuprofen',                 'Reckitt Benckiser','otc','Box of 24 Tablets',          'NSAID for pain, fever, and inflammation.',                               'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&q=80', true, false),
('Cetirizine 10mg',         'Cetirizine HCl',            'UCB Pharma',      'otc', 'Box of 30 Tablets',          'Second-generation antihistamine for allergic rhinitis.',                 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80', true, false),
('Loratadine 10mg',         'Loratadine',                'Schering-Plough', 'otc', 'Box of 30 Tablets',          'Non-drowsy antihistamine for allergy relief.',                           'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=600&q=80', true, false),
('Dextromethorphan 15mg',   'Dextromethorphan HBr',      'Pfizer Inc.',     'otc', 'Box of 20 Capsules',         'Cough suppressant for dry cough relief.',                                'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=600&q=80', true, false),
('Antacid Tablets',         'Calcium Carbonate',         'Reckitt Benckiser','otc','Roll of 40 Tablets',         'Fast-acting antacid for heartburn and indigestion.',                     'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&q=80', true, false),
('Loperamide 2mg',          'Loperamide HCl',            'Johnson & Johnson','otc','Box of 12 Capsules',         'Antidiarrheal for acute and chronic diarrhea.',                          'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&q=80', true, false),
('Dettol Antiseptic 500ml', 'Chloroxylenol 4.8%',        'RB Health',       'otc', '500ml Bottle',               'Antiseptic liquid for wound cleaning and disinfection.',                 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&q=80', true, false),
('Zinc Oxide Cream',        'Zinc Oxide 15%',            'Generic Pharma',  'otc', '50g Tube',                   'Protective barrier cream for skin irritation and nappy rash.',          'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=600&q=80', true, false),
('Oral Rehydration Salts',  'Sodium Chloride/Glucose',   'WHO Formula',     'otc', 'Box of 20 Sachets',          'WHO-standard ORS for dehydration from diarrhea and vomiting.',          'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80', true, false),

-- ── MEDICAL SUPPLIES ─────────────────────────────────────────────────────────
('N95 Respirator Mask',     'Filtering Facepiece',       'MedShield',       'medical-supplies', 'Box of 20 Masks',            'NIOSH-approved N95 respirator for healthcare settings.',                 'https://images.unsplash.com/photo-1584634731339-252c581abfc5?w=600&q=80', true, false),
('Disposable Gloves M',     'Nitrile Examination Gloves','Ansell',          'medical-supplies', 'Box of 100 Gloves',          'Powder-free nitrile gloves for clinical examination.',                   'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=600&q=80', true, false),
('IV Infusion Set',         'Sterile IV Administration', 'B. Braun',        'medical-supplies', 'Box of 50 Sets',             'Standard IV infusion set with 15 drops/ml drip chamber.',               'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80', true, false),
('Sterile Gauze Pads 4x4',  'Sterile Cotton Gauze',      'Medline',         'medical-supplies', 'Box of 200 Pads',            'Sterile woven gauze for wound dressing and cleaning.',                   'https://images.unsplash.com/photo-1584634731339-252c581abfc5?w=600&q=80', true, false),
('Adhesive Bandages',       'Sterile Wound Closure',     '3M Healthcare',   'medical-supplies', 'Box of 100 Strips',          'Flexible fabric adhesive bandages for minor wounds.',                    'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=600&q=80', true, false),
('Syringe 5ml',             'Sterile Disposable Syringe','BD Medical',      'medical-supplies', 'Box of 100 Syringes',        'Luer-lock sterile syringe for injection and aspiration.',                'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80', true, false),
('Hypodermic Needle 21G',   'Sterile Hypodermic Needle', 'BD Medical',      'medical-supplies', 'Box of 100 Needles',         '21 gauge x 1.5 inch sterile needle for intramuscular injection.',       'https://images.unsplash.com/photo-1584634731339-252c581abfc5?w=600&q=80', true, false),
('Wound Dressing 10x10cm',  'Non-Adherent Dressing',     'Smith & Nephew',  'medical-supplies', 'Box of 50 Dressings',        'Non-adherent wound contact layer for moderate exudate wounds.',         'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=600&q=80', true, false),
('Elastic Bandage 10cm',    'Cohesive Elastic Bandage',  'Medline',         'medical-supplies', 'Box of 12 Rolls',            'Self-adhesive elastic bandage for compression and support.',            'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80', true, false),
('Urine Collection Bag',    'Sterile Drainage Bag',      'Coloplast',       'medical-supplies', 'Box of 10 Bags',             '2000ml sterile urinary drainage bag with anti-reflux valve.',           'https://images.unsplash.com/photo-1584634731339-252c581abfc5?w=600&q=80', true, false),
('Oxygen Mask Adult',       'Non-Rebreather Oxygen Mask','Intersurgical',   'medical-supplies', 'Box of 10 Masks',            'High-concentration oxygen mask with reservoir bag for adults.',         'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=600&q=80', true, false),

-- ── SURGICAL ─────────────────────────────────────────────────────────────────
('Surgical Gloves L',       'Latex Examination Gloves',  'Ansell',          'surgical', 'Box of 100 Pairs',           'Sterile latex gloves for surgical procedures.',                          'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=600&q=80', true, false),
('Scalpel Handle No.4',     'Stainless Steel Handle',    'Swann-Morton',    'surgical', 'Pack of 5 Handles',          'Reusable stainless steel scalpel handle for No.20-25 blades.',          'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80', true, false),
('Surgical Suture 2-0',     'Polyglycolic Acid Suture',  'Ethicon',         'surgical', 'Box of 12 Sutures',          'Absorbable braided suture for soft tissue approximation.',               'https://images.unsplash.com/photo-1584634731339-252c581abfc5?w=600&q=80', true, false),
('Surgical Drape 150x200cm','Sterile Surgical Drape',    '3M Healthcare',   'surgical', 'Box of 20 Drapes',           'Sterile disposable surgical drape for operating field isolation.',       'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=600&q=80', true, false),
('Electrosurgical Pencil',  'Monopolar ESU Pencil',      'Covidien',        'surgical', 'Box of 50 Pencils',          'Disposable electrosurgical pencil with push-button activation.',        'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80', true, false),
('Surgical Stapler 30mm',   'Linear Cutting Stapler',    'Ethicon',         'surgical', 'Pack of 5 Staplers',         '30mm linear cutting stapler for gastrointestinal anastomosis.',         'https://images.unsplash.com/photo-1584634731339-252c581abfc5?w=600&q=80', true, false),
('Retractor Set',           'Stainless Steel Retractors','Aesculap',        'surgical', 'Set of 6 Retractors',        'Stainless steel wound retractor set for abdominal surgery.',            'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=600&q=80', true, false),
('Surgical Gown XL',        'Sterile Surgical Gown',     'Medline',         'surgical', 'Box of 20 Gowns',            'Sterile reinforced surgical gown with knit cuffs.',                     'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80', true, false),
('Bone Saw Blade',          'Oscillating Saw Blade',     'Stryker',         'surgical', 'Pack of 10 Blades',          'Sterile oscillating saw blade for orthopedic procedures.',              'https://images.unsplash.com/photo-1584634731339-252c581abfc5?w=600&q=80', true, false),
('Laparoscopic Trocar 5mm', 'Disposable Trocar',         'Covidien',        'surgical', 'Box of 10 Trocars',          '5mm disposable trocar with safety shield for laparoscopic surgery.',    'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=600&q=80', true, false),

-- ── LABORATORY ───────────────────────────────────────────────────────────────
('Blood Glucose Meter',     'Glucometer',                'Roche Diagnostics','laboratory','1 Device + 10 Strips',      'Portable blood glucose monitoring system with memory.',                 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=600&q=80', true, false),
('PCR Test Kit COVID-19',   'RT-PCR Diagnostic Kit',     'Roche Diagnostics','laboratory','Box of 96 Tests',           'Real-time PCR kit for SARS-CoV-2 detection.',                           'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80', true, false),
('Centrifuge Tubes 15ml',   'Polypropylene Tubes',       'Corning',         'laboratory', 'Rack of 50 Tubes',          'Sterile conical centrifuge tubes for sample processing.',               'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=600&q=80', true, false),
('Microscope Slides',       'Borosilicate Glass Slides', 'Thermo Fisher',   'laboratory', 'Box of 72 Slides',          'Pre-cleaned borosilicate glass slides for histology.',                  'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80', true, false),
('Urine Dipstick 10 Panel', 'Multi-Parameter Urinalysis','Siemens',         'laboratory', 'Bottle of 100 Strips',      '10-parameter urine test strips for routine urinalysis.',               'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=600&q=80', true, false),
('Hemoglobin Analyzer',     'Point-of-Care Hb Analyzer', 'HemoCue',         'laboratory', '1 Analyzer + 50 Cuvettes',  'Portable hemoglobin analyzer for anemia screening.',                    'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80', true, false),
('Blood Culture Bottles',   'Aerobic/Anaerobic Bottles', 'BD BACTEC',       'laboratory', 'Box of 20 Bottles',         'Automated blood culture bottles for bacteremia detection.',             'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=600&q=80', true, false),
('Pipette Tips 200ul',      'Universal Pipette Tips',    'Eppendorf',       'laboratory', 'Rack of 96 Tips',           'Universal fit pipette tips for 200ul volume range.',                    'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80', true, false),
('Malaria RDT Kit',         'Rapid Diagnostic Test',     'SD Biosensor',    'laboratory', 'Box of 25 Tests',           'Rapid malaria antigen detection for P. falciparum and P. vivax.',      'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=600&q=80', true, false),
('Pregnancy Test Strip',    'hCG Rapid Test',            'Clearblue',       'laboratory', 'Box of 50 Strips',          'Highly sensitive urine hCG test for early pregnancy detection.',        'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80', true, false),

-- ── PERSONAL CARE ────────────────────────────────────────────────────────────
('Vitamin D3 1000IU',       'Cholecalciferol',           'NutraCare',       'personal-care', '90 Softgel Capsules',        'Vitamin D3 supplement for bone health and immunity.',                   'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&q=80', true, false),
('Vitamin C 1000mg',        'Ascorbic Acid',             'NutraCare',       'personal-care', '90 Effervescent Tablets',    'High-dose vitamin C for immune support and antioxidant protection.',   'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&q=80', true, true),
('Omega-3 Fish Oil 1000mg', 'EPA/DHA Omega-3',           'Nordic Naturals', 'personal-care', '90 Softgel Capsules',        'Pharmaceutical-grade omega-3 for cardiovascular and brain health.',    'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&q=80', true, false),
('Zinc 50mg',               'Zinc Gluconate',            'Solgar',          'personal-care', 'Box of 100 Tablets',         'Zinc supplement for immune function and wound healing.',                'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&q=80', true, false),
('Magnesium 400mg',         'Magnesium Oxide',           'Nature Made',     'personal-care', 'Box of 60 Tablets',          'Magnesium supplement for muscle function and sleep quality.',          'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&q=80', true, false),
('Probiotic 10 Billion CFU','Multi-Strain Probiotic',    'Culturelle',      'personal-care', 'Box of 30 Capsules',         '10 billion CFU probiotic for digestive health and immunity.',          'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&q=80', true, false),
('Iron 65mg',               'Ferrous Sulfate',           'Slow Fe',         'personal-care', 'Box of 60 Tablets',          'Slow-release iron supplement for iron deficiency anemia.',             'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&q=80', true, false),
('Folic Acid 5mg',          'Pteroylglutamic Acid',      'Generic Pharma',  'personal-care', 'Box of 100 Tablets',         'Folic acid for neural tube defect prevention in pregnancy.',           'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&q=80', true, false),
('Multivitamin Complete',   'Multi-Vitamin/Mineral',     'Centrum',         'personal-care', 'Box of 60 Tablets',          'Complete daily multivitamin with 23 essential nutrients.',             'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&q=80', true, false),
('Calcium 600mg + D3',      'Calcium Carbonate + D3',    'Caltrate',        'personal-care', 'Box of 60 Tablets',          'Calcium and vitamin D3 combination for bone density.',                 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&q=80', true, false)

ON CONFLICT DO NOTHING;

-- Verify count
SELECT category, COUNT(*) as total FROM products WHERE is_active = true GROUP BY category ORDER BY category;
